FROM osrf/ros:jazzy-desktop-full

# --- Dependencias del sistema ---
RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    git \
    curl \
    gnupg \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# --- Gazebo Harmonic + ROS-GZ bridge ---
RUN apt-get update && apt-get install -y \
    ros-jazzy-ros-gz \
    ros-jazzy-ros-gz-sim \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-gz-ros2-control \
    && rm -rf /var/lib/apt/lists/*

# --- Paquetes ROS necesarios (equivalentes a los de Humble) ---
RUN apt-get update && apt-get install -y \
    ros-jazzy-irobot-create-msgs \
    ros-jazzy-navigation2 \
    ros-jazzy-nav2-bringup \
    ros-jazzy-nav2-rviz-plugins \
    ros-jazzy-joint-state-publisher \
    ros-jazzy-ros2-controllers \
    ros-jazzy-joint-state-broadcaster \
    ros-jazzy-control-msgs \
    ros-jazzy-rsl \
    && rm -rf /var/lib/apt/lists/*

# --- SLAM Toolbox desde apt ---
RUN apt-get update && apt-get install -y \
    ros-jazzy-slam-toolbox \
    && rm -rf /var/lib/apt/lists/*

# --- Modelos de Gazebo (opcional) ---
RUN git clone https://github.com/osrf/gazebo_models.git /usr/share/gazebo/models

# --- Dependencias Python ---
# PyQt5 y PyQtGraph desde apt (más estable en Jazzy)
#RUN apt-get update && apt-get install -y \
#    python3-pyqt5 \
#    python3-pyqtgraph

# Resto de dependencias Python vía pip
#RUN pip3 install --no-cache-dir --break-system-packages \
#    "numpy<2" \
#    pandas \
#    lxml \
#    pipreqs \
#    setuptools==59.6.0


# --- PyTorch con CUDA 11.3 ---
#RUN pip3 install --break-system-packages torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu113

#RUN pip3 install --break-system-packages \
#    --index-url https://download.pytorch.org/whl/nightly/cu121 \
#    torch torchvision torchaudio


# --- Variables de entorno ---
ENV GZ_SIM_RESOURCE_PATH=/usr/share/gazebo/models
ENV GAZEBO_MODEL_PATH=/usr/share/gazebo/models

# --- Copiar entrypoint ---
COPY ./ros_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/bin/bash"]
